# https://github.com/daaannorris/Magento2

version: '2'
services:
  apache:
    image: daaannorris/magento2
    # build: .
    ports:
      - "8084:80" # web
      - "9001:9000" # xdebug
      # - "35729:35729" # live reload
    volumes:
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
      - ../composer.json:/var/www/html/composer.json
      - ../composer.lock:/var/www/html/composer.lock
      - ../app/code:/var/www/html/app/code
      - ../app/design/frontend:/var/www/html/app/design/frontend
      - ../var/report:/var/www/html/var/report
      - ../var/log:/var/www/html/var/log
      # - ~/.nvm:/var/www/.nvm
    environment:
      XDEBUG_CONFIG: "remote_host=localhost"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    links:
      - db
    networks:
      - <project_name>-network

  db:
    image: mariadb
    ports:
     - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - <project_name>-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - 8080:80
    networks:
      - <project_name>-network

  redis:
    image: redis
    ports:
     - 6379
    networks:
      - <project_name>-network

  redis-session:
    image: redis
    ports:
     - 6379
    networks:
      - <project_name>-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - <project_name>-network

networks:
  <project_name>-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
